#!/bin/bash  

echo "itempest user data" >> itempest-userdata  
chmod 777 itempest-userdata  
export OS_USERNAME=demo
export OS_PASSWORD=openstack
export OS_TENANT_NAME=demo
export OS_AUTH_URL='http://10.8.3.1:5000/v2.0'
export MDSERV=http://169.254.169.254/
export OS_MDSERV=http://169.254.169.254/openstack
